import type { SectionMeta } from './types'

export const sections: SectionMeta[] = [
  { id: 'rk_attribution', group: 'Where is the risk coming from?', title: 'Return and risk attribution', keys: ['high-vol driver', 'sharpe (1y)', 'realised vol', '1σ swing', 'risk-adjusted'] },
  { id: 'rk_dollar_risk', group: 'Where is the risk coming from?', title: 'Dollar risk', keys: ['1σ swing', 'correction', 'bear market', 'crash', 'SPX −15%', 'SPX −30%', 'SPX −45%', 'beta'] },
  { id: 'rk_vol_attribution', group: 'Where is the risk coming from?', title: 'Volatility attribution', keys: ['share of portfolio variance', 'volatility', 'weight', 'σ', 'vol driver', 'other'] },
  { id: 'rk_alerts', group: 'Where is the risk coming from?', title: 'System alerts', keys: ['alerts', 'active alerts', 'unified alerts', 'red', 'warning'] },
  { id: 'rk_regime', group: 'Market regime', title: 'Market regime and positioning', keys: ['regime', 'VIX', 'alignment', 'growth vs income', 'positioning', 'expansion', 'risk-off'] },
  { id: 'rk_regime_transition', group: 'Market regime', title: 'Regime transition risk', adv: true, keys: ['current regime', 'transition probabilities', 'est. half-life', '20D momentum', '90D trend', 'signal tension', 'fragility', 'consolidation', 'acceleration'] },
  { id: 'rk_regime_alignment', group: 'Market regime', title: 'Regime alignment', adv: true, keys: ['alignment score', 'positioning', 'regime', 'aggressive', 'balanced', 'conservative'] },
  { id: 'rk_risk_adjusted', group: 'Market regime', title: 'Risk-adjusted returns', adv: true, keys: ['sharpe', 'risk-adjusted', 'top holdings by weight', 'return', 'volatility'] },
  { id: 'rk_structure', group: 'Correlation and structure', title: 'Portfolio structure', keys: ['top holding', 'top 5 weight', 'effective holdings', 'correlation risk', 'concentration', 'overlap'] },
  { id: 'rk_corr_matrix', group: 'Correlation and structure', title: 'Correlation clusters', adv: true, keys: ['correlation matrix', 'correlation clusters', 'growth', 'CEF', 'dividend'] },
  { id: 'rk_cross_sleeve', group: 'Correlation and structure', title: 'Cross-sleeve correlation', adv: true, keys: ['cross-sleeve', 'correlation', 'diversification score', 'sleeve'] },
  { id: 'rk_stress_corr', group: 'Correlation and structure', title: 'Stress correlation', adv: true, keys: ['cluster risk', 'highest stress pairs', 'stress uplift', 'vs normal regime', 'growth', 'CEF', 'dividend'] },
  { id: 'rk_heatmap', group: 'Correlation and structure', title: 'Portfolio heatmap', adv: true, keys: ['return vs risk contribution', 'contribution detail', 'RET%', 'RISK%', 'INC%'] },
  { id: 'rk_beta', group: 'Drawdown and volatility', title: 'Beta decomposition', adv: true, keys: ['beta', 'weighted beta', 'beta contribution', 'vs SPY'] },
  { id: 'rk_drawdown_path', group: 'Drawdown and volatility', title: 'Drawdown path', adv: true, keys: ['drawdown', 'top DD contributors (6M)', 'max drawdown', 'recovery'] },
  { id: 'rk_vol_budget_trend', group: 'Drawdown and volatility', title: 'Vol budget trend', adv: true, keys: ['vol budget', 'current', '1M est.', '3M est.', '6M est.', 'top vol drivers'] },
  { id: 'rk_cash', group: 'Cash, execution and tax', title: 'Cash and execution', keys: ['cash runway', 'withdrawal mode', 'monthly need', 'active alerts', 'spendable', 'money market'] },
  { id: 'rk_execution', group: 'Cash, execution and tax', title: 'Execution signals', keys: ['execution signals', 'BUY', 'TRIM', 'REDUCE', 'HOLD', 'EXIT', 'WATCH', 'overweight', 'target drift'] },
  { id: 'rk_liquidity', group: 'Cash, execution and tax', title: 'Liquidity', adv: true, keys: ['liquidity', 'cash locations', 'taxable', 'Roth', 'rollover', 'IRA'] },
  { id: 'rk_tax_income', group: 'Cash, execution and tax', title: 'Tax and income', keys: ['income durability', 'tax status', 'income per month', 'spending per month', 'bracket'] },
  { id: 'rk_tax_drift', group: 'Cash, execution and tax', title: 'Tax drift', adv: true, keys: ['bracket pace', 'bracket status', 'NIIT exposure', 'conv cap', 'bracket', 'critical'] },
  { id: 'rk_cashflow_vol', group: 'Cash, execution and tax', title: 'Cashflow volatility', adv: true, keys: ['cashflow volatility', 'income by ticker', 'dividend variability', 'monthly income'] },
]
