import type { SectionMeta, SubTabMeta } from './types'

export const sections: SectionMeta[] = [
  { id: 'tx_income', group: 'Tax planning · Where am I this year?', sub: 'tax', title: 'Income summary', keys: ['W2 salary', 'dividends taxable', 'Roth conversion', 'projected gross', 'income mix', 'tax bracket', 'over ceiling', 'marginal rate'] },
  { id: 'tx_meter', group: 'Tax planning · Where am I this year?', sub: 'tax', title: 'Bracket meter', keys: ['bracket used', 'bracket room', 'safe', 'moderate', 'high', 'gross ceiling', 'std deduction'] },
  { id: 'tx_position', group: 'Tax planning · Where am I this year?', sub: 'tax', title: 'Tax position', keys: ['effective tax rate', 'tax drag', 'conversion opportunity', 'conversion room', 'conversion score', 'converted YTD'] },
  { id: 'tx_briefing', group: 'Tax planning · Where am I this year?', sub: 'tax', title: 'Tax briefing', keys: ['bracket fullness', 'AGI estimate', 'qualified dividends', 'ordinary dividends', 'bracket pressure'] },
  { id: 'tx_payments', group: 'Tax planning · Estimated payments', sub: 'tax', title: 'Estimated tax payments', keys: ['safe harbor', 'quarterly', 'Q1', 'Q2', 'Q3', 'Q4', 'due date', 'payment readiness', 'IRS'] },
  { id: 'tx_accounts', group: 'Tax planning · Accounts and outlook', sub: 'tax', title: 'Account structure', keys: ['tax exposure', 'pre-tax IRA', 'Roth IRA', 'taxable', 'tax cost YTD', 'annual RMD impact', 'breakeven'] },
  { id: 'tx_forward', group: 'Tax planning · Accounts and outlook', sub: 'tax', title: 'Forward planning', keys: ['RMD start', 'Social Security start', 'IRMAA', 'Medicare start'] },
  { id: 'tx_scores', group: 'Tax planning · Accounts and outlook', sub: 'tax', title: 'Portfolio tax scores', keys: ['personal profile', 'filing status', 'spouse', 'bracket headroom', 'income tax efficiency', 'sequence risk score', 'conversion efficiency', 'annual conversion target'] },
  { id: 'tx_divchar', group: "Tax planning · What's driving the tax bill", sub: 'tax', title: 'Dividend tax character', adv: true, keys: ['ordinary', 'qualified', 'return of capital', 'ROC'] },
  { id: 'tx_perfund', group: "Tax planning · What's driving the tax bill", sub: 'tax', title: 'Per-fund dividend character', adv: true, keys: ['ROC-heavy', 'qualified-heavy', 'ordinary-heavy', 'per fund'] },
  { id: 'tx_calendar', group: "Tax planning · What's driving the tax bill", sub: 'tax', title: 'Taxable dividend calendar', adv: true, keys: ['monthly dividends', 'payout calendar', 'ex-date'] },
  { id: 'tx_realized', group: "Tax planning · What's driving the tax bill", sub: 'tax', title: 'Realized sales — capital gains tax', adv: true, keys: ['STCG', 'LTCG', 'realized gains', 'cap gains tax'] },
  { id: 'tx_ss', group: 'Tax planning · Social Security', sub: 'tax', title: 'Social Security options', adv: true, keys: ['claiming age', 'SS at 62', 'SS at 67', 'SS at 70', 'benefit'] },
  { id: 'tx_with_ss', group: 'Tax planning · Social Security', sub: 'tax', title: 'With Social Security — tax scenario', adv: true, keys: ['taxable Social Security', 'provisional income', 'effective rate with SS'] },
  { id: 'tx_cashflow', group: 'Tax planning · Withdrawals and rebalancing', sub: 'tax', title: 'Tax-aware cashflow', adv: true, keys: ['after-tax cashflow', 'spending', 'tax reserve'] },
  { id: 'tx_rebal_score', group: 'Tax planning · Withdrawals and rebalancing', sub: 'tax', title: 'Tax-efficient rebalance score', adv: true, keys: ['rebalance score', 'tax cost of rebalancing'] },
  { id: 'tx_withdrawal', group: 'Tax planning · Withdrawals and rebalancing', sub: 'tax', title: 'Withdrawal tax sequencing', adv: true, keys: ['withdrawal state', 'withdrawal order', 'sequencing'] },
  { id: 'tx_r_command', group: 'Roth conversion · Should I convert now?', sub: 'roth', title: 'Conversion command center', keys: ['conversion verdict', 'GO', 'WAIT', 'STOP', 'recommended target', 'income confidence'] },
  { id: 'tx_r_stop', group: 'Roth conversion · Should I convert now?', sub: 'roth', title: 'Stop verdict', keys: ['stop', 'bracket-fill option', 'not recommended'] },
  { id: 'tx_r_exec', group: 'Roth conversion · Should I convert now?', sub: 'roth', title: 'Execution month action', keys: ['execution checklist', 'conversion month', 'December'] },
  { id: 'tx_r_window', group: 'Roth conversion · Should I convert now?', sub: 'roth', title: 'Window status', keys: ['window status', 'blockers', 'income received', 'trigger'] },
  { id: 'tx_r_bracket', group: 'Roth conversion · Should I convert now?', sub: 'roth', title: 'Bracket filling engine', keys: ['bracket room', 'safe room', 'safety buffer', 'target bracket', 'math rule action', 'window status'] },
  { id: 'tx_r_status', group: 'Roth conversion · Progress this year', sub: 'roth', title: 'Conversion status and progress', keys: ['converted YTD', 'conversion target', 'progress', 'rollover balance', 'max additional'] },
  { id: 'tx_r_scen', group: 'Roth conversion · Progress this year', sub: 'roth', title: 'Conversion scenarios', keys: ['recommended scenario', 'conservative', 'aggressive'] },
  { id: 'tx_r_income', group: 'Roth conversion · Progress this year', sub: 'roth', title: 'Income summary', keys: ['projected gross', 'income mix'] },
  { id: 'tx_r_runway', group: 'Roth conversion · Lifetime plan', sub: 'roth', title: 'Conversion runway', keys: ['rollover depletion', 'years remaining', 'depletion age'] },
  { id: 'tx_r_rmd', group: 'Roth conversion · Lifetime plan', sub: 'roth', title: 'RMD-only vs conversion — lifetime', keys: ['RMD', 'lifetime tax', 'partial conversion', 'full conversion', 'age 90'] },
  { id: 'tx_r_calendar', group: 'Roth conversion · Lifetime plan', sub: 'roth', title: 'Conversion schedule — rollover depletion', adv: true, keys: ['depletion schedule', 'multi-year', 'why not converting'] },
  { id: 'tx_r_proj', group: 'Roth conversion · Lifetime plan', sub: 'roth', title: 'Long-term projection', adv: true, keys: ['projection', 'Roth balance', 'rollover balance'] },
  { id: 'tx_r_logic', group: 'Roth conversion · Engine detail', sub: 'roth', title: 'Room and AGI calculation engine', adv: true, keys: ['AGI', 'room', 'MAGI', 'actual YTD AGI', 'full-year AGI estimate', 'conversion score', 'timing engine'] },
  { id: 'tx_r_acct', group: 'Roth conversion · Engine detail', sub: 'roth', title: 'Account allocation impact', adv: true, keys: ['account allocation', 'Roth plan', 'safe room'] },
  { id: 'tx_r_taximpact', group: 'Roth conversion · Engine detail', sub: 'roth', title: 'Conversion tax impact', adv: true, keys: ['conversion tax', 'IRMAA', 'marginal'] },
  { id: 'tx_s_lots', group: 'Sell and rebalance · Which lots to sell?', sub: 'sell', title: 'Lot signals', keys: ['tax lots', 'LTCG unrealized', 'STCG unrealized', 'STCG tax if sold now', 'savings from waiting', 'harvestable loss', 'LTCG room', 'maturity calendar'] },
  { id: 'tx_s_gain', group: 'Sell and rebalance · Which lots to sell?', sub: 'sell', title: 'Gain planner', adv: true, keys: ['manual lot pick', 'gain budget', 'exclude income'] },
  { id: 'tx_s_detail', group: 'Sell and rebalance · Which lots to sell?', sub: 'sell', title: 'Lot details', keys: ['per-position', 'lot table', 'sell signal', 'WAIT', 'HARVEST', 'FREE', 'data coverage'] },
  { id: 'tx_s_maturity', group: 'Sell and rebalance · Gain classification', sub: 'sell', title: 'Lot maturity and gain classification', keys: ['long-term', 'short-term', 'lot maturity'] },
  { id: 'tx_s_pipeline', group: 'Sell and rebalance · Gain classification', sub: 'sell', title: 'Tax pipeline — ordinary vs capital gains', keys: ['ordinary income', 'capital gains', 'pipeline'] },
  { id: 'tx_s_plan', group: 'Sell and rebalance · Multi-year plan', sub: 'sell', title: 'Multi-year rebalance plan', keys: ['sell plan', 'rebalance', 'bracket ceiling', 'NIIT', 'multi-year'] },
]

export const subTabs: SubTabMeta[] = [
  { id: 'tax', label: 'Tax planning' },
  { id: 'roth', label: 'Roth conversion' },
  { id: 'sell', label: 'Sell and rebalance' },
]
